---
- name: "Validate Core Reachability"
  hosts: junos
  tasks:
    - name: "Ping Across All Loopback Interfaces"
      junos_ping:
        dest: "{{ item.value.split('/')[0] }}"
        interface: lo0.0
        size: 512
      with_dict: "{{lo_ip}}"
      vars:
        ansible_connection: network_cli
      register: ping_rst
      ignore_errors: yes

    - debug: var=ping_rst
      run_once: yes

    - name: Create Ping Report
      blockinfile:
        block: |

            Src Node | Dest Node | Dest IP | Packet Loss | Delay |
            -----| ------------| ------------| ------|
            {%  for node in play_hosts %}
            {%    for result in hostvars[node].ping_rst.results %}
            {%      if result.rtt is defined %}
            {{ node }} | {{ result.item.key }} |{{ result.item.value }} | {{ result.packet_loss }} | {{ result.rtt.avg }}
            {%      else %}
            {{ node }} | {{ result.item.key }} |{{ result.item.value }} | {{ result.packet_loss }} | 'N/A'
            {%      endif %}
            {%    endfor %}
            {%  endfor %}


        path: ./ping_report.md
        create: yes
      run_once: yes
        
