---
- name: Return Juniper Network to Default
  hosts: junos
  tasks:
    - name: Delete Configuration
      junos_config:
        lines:
          - delete interfaces ge-0/0/0
          - delete interfaces ge-0/0/1
          - delete interfaces ge-0/0/2
          - delete interfaces ge-0/0/3
          - delete system login user ansible
          - delete protocols
          - delete routing-instances
          - delete system name-server
          - delete system services netconf 
        src_format: set
      tags: deploy